### ISSUE TITLE
Not Working, youtube-dl redirect the video link 

### ISSUE THREAD

**Issue by dw-liedji** [TimilsinaBimal/freetutorials-dl#1] opened 2020-12-27 20:02 UTC
[generic] 0: Requesting header
[redirect] Following redirect to https://www.freetutorials.ca/video/mastering-react/10/0
[generic] 0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0: Downloading webpage
[generic] 0: Extracting information
ERROR: unable to download video data: HTTP Error 404: Not Found
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py in process_info(self, info_dict)
   1935                     # Just a single file
-> 1936                     success = dl(filename, info_dict)
   1937             except (compat_urllib_error.URLError, compat_http_client.HTTPException, socket.error) as err:

~/anaconda3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py in dl(name, info)
   1874                         self.to_screen('[debug] Invoking downloader on %r' % info.get('url'))
-> 1875                     return fd.download(name, info)
   1876 

~/anaconda3/lib/python3.8/site-packages/youtube_dl/downloader/common.py in download(self, filename, info_dict)
    365 
--> 366         return self.real_download(filename, info_dict)
    367 

~/anaconda3/lib/python3.8/site-packages/youtube_dl/downloader/http.py in real_download(self, filename, info_dict)
    350             try:
--> 351                 establish_connection()
    352                 return download()

~/anaconda3/lib/python3.8/site-packages/youtube_dl/downloader/http.py in establish_connection()
    115                         raise RetryDownload(err)
--> 116                     raise err
    117                 # When trying to resume, Content-Range HTTP header of response has to be checked

~/anaconda3/lib/python3.8/site-packages/youtube_dl/downloader/http.py in establish_connection()
    109                 try:
--> 110                     ctx.data = self.ydl.urlopen(request)
    111                 except (compat_urllib_error.URLError, ) as err:

~/anaconda3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py in urlopen(self, req)
   2247             req = sanitized_Request(req)
-> 2248         return self._opener.open(req, timeout=self._socket_timeout)
   2249 

~/anaconda3/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 

~/anaconda3/lib/python3.8/urllib/request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)

~/anaconda3/lib/python3.8/urllib/request.py in error(self, proto, *args)
    562         args = (dict, proto, meth_name) + args
--> 563         result = self._call_chain(*args)
    564         if result:

~/anaconda3/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:

~/anaconda3/lib/python3.8/urllib/request.py in http_error_302(self, req, fp, code, msg, headers)
    754 
--> 755         return self.parent.open(new, timeout=req.timeout)
    756 

~/anaconda3/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 

~/anaconda3/lib/python3.8/urllib/request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)

~/anaconda3/lib/python3.8/urllib/request.py in error(self, pr

**Comment by TimilsinaBimal** [comment] 2020-12-28 06:59
Thank you for the issue! The problem is fixed now!
c073f0f78510b06badc12f4177ce8e92bc255492

**Closed as completed by TimilsinaBimal** 2020-12-28 06:59 UTC
